# Header
menu:
  Home: /
banner: images/book.webp
subtitle: The hunt for the match

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5
# Footer
copyright: |-
  All content on this site excluding the banner image is Copyright Will Shadow 2020. 
  <br>No parts of the stories listed here may be reproduced without express permission, which can be obtained at <a href="mailto:will@theshadow.xyz">this email</a>

# Sidebar
sidebar: right
widgets:
- category
- recent_posts

# Miscellaneous
favicon: /favicon.png
